import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import toast from "react-hot-toast";
import api from "../lib/api";
import { socket } from "../lib/socket";
import Loading from "../components/Loading";
import { Empty } from "./ProductsPage";
import { useAuth } from "../context/AuthContext";

const categories = ["boxes", "mailers", "bags", "bottles", "containers", "wraps", "labels", "protective", "other"];
const Status = ({ value }) => <span className="rounded-full bg-mist px-2.5 py-1 text-xs font-semibold capitalize text-forest">{value}</span>;
const Field = ({ label, children }) => <label className="block"><span className="label">{label}</span>{children}</label>;

export function ProductManagementPage() {
  const [products, setProducts] = useState(null); const [editing, setEditing] = useState(null);
  const load = async () => { try { const { data } = await api.get("/products/mine"); setProducts(data.products); } catch (error) { toast.error(error.response?.data?.message || "Could not load products."); setProducts([]); } };
  useEffect(() => { load(); }, []);
  const remove = async (id) => { if (!window.confirm("Delete this product listing?")) return; try { await api.delete(`/products/${id}`); toast.success("Product deleted."); load(); } catch (error) { toast.error(error.response?.data?.message || "Could not delete product."); } };
  if (!products) return <Loading />;
  return <section className="py-10"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-semibold text-leaf">SUPPLIER CATALOG</p><h1 className="mt-2 text-4xl text-forest">Manage products</h1></div><button className="btn-primary" onClick={() => setEditing({})}>Add product</button></div>{editing && <ProductForm product={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); load(); }} />}<div className="mt-7 space-y-3">{products.map((product) => <article className="card flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center" key={product._id}><div><h2 className="font-semibold text-forest">{product.name}</h2><p className="mt-1 text-sm text-slate-500">{product.material} · {product.currency} {product.price} · MOQ {product.minimumOrderQuantity}</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={() => setEditing(product)}>Edit</button><button className="btn-secondary text-red-700" onClick={() => remove(product._id)}>Delete</button></div></article>)}</div>{!products.length && <div className="mt-7"><Empty title="No products listed" copy="Add your first product to receive RFQs." /></div>}</section>;
}

function ProductForm({ product, onClose, onSaved }) {
  const { register, handleSubmit, formState: { isSubmitting } } = useForm({ defaultValues: { name: product.name || "", description: product.description || "", category: product.category || "boxes", material: product.material || "", price: product.price || "", currency: product.currency || "USD", minimumOrderQuantity: product.minimumOrderQuantity || "", leadTimeDays: product.leadTimeDays || "", ecoScore: product.sustainability?.score || "", recyclable: product.sustainability?.recyclable || false, compostable: product.sustainability?.compostable || false } });
  const submit = async (values) => { const payload = { ...values, price: Number(values.price), minimumOrderQuantity: Number(values.minimumOrderQuantity), leadTimeDays: values.leadTimeDays ? Number(values.leadTimeDays) : undefined, sustainability: { score: values.ecoScore ? Number(values.ecoScore) : undefined, recyclable: values.recyclable, compostable: values.compostable } }; try { if (product._id) await api.patch(`/products/${product._id}`, payload); else await api.post("/products", payload); toast.success("Product saved."); onSaved(); } catch (error) { toast.error(error.response?.data?.message || "Could not save product."); } };
  return <div className="card mt-7 p-6"><div className="flex justify-between"><h2 className="text-xl">{product._id ? "Edit product" : "New product"}</h2><button onClick={onClose}>Close</button></div><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={handleSubmit(submit)}><Field label="Product name"><input className="input" required {...register("name")} /></Field><Field label="Material"><input className="input" required {...register("material")} /></Field><Field label="Category"><select className="input" {...register("category")}>{categories.map((category) => <option key={category}>{category}</option>)}</select></Field><Field label="Price per unit"><input className="input" required type="number" min="0" step="0.01" {...register("price")} /></Field><Field label="Currency"><input className="input" maxLength="3" {...register("currency")} /></Field><Field label="Minimum order quantity"><input className="input" required type="number" min="1" {...register("minimumOrderQuantity")} /></Field><Field label="Lead time (days)"><input className="input" type="number" min="0" {...register("leadTimeDays")} /></Field><Field label="Eco score"><input className="input" type="number" min="0" max="100" {...register("ecoScore")} /></Field><label className="md:col-span-2"><span className="label">Description</span><textarea className="input min-h-24" required {...register("description")} /></label><div className="flex gap-5 md:col-span-2"><label><input className="mr-2" type="checkbox" {...register("recyclable")} />Recyclable</label><label><input className="mr-2" type="checkbox" {...register("compostable")} />Compostable</label></div><div className="flex gap-3 md:col-span-2"><button className="btn-primary" disabled={isSubmitting}>Save product</button><button className="btn-secondary" type="button" onClick={onClose}>Cancel</button></div></form></div>;
}

export function QuotesPage() {
  const { user } = useAuth(); const [quotes, setQuotes] = useState(null); const [selected, setSelected] = useState(null);
  useEffect(() => { const load = async () => { try { const { data } = await api.get("/quotes"); setQuotes(data.quotes); } catch (error) { toast.error(error.response?.data?.message || "Could not load quotations."); setQuotes([]); } }; load(); }, []);
  if (!quotes) return <Loading />;
  const updateQuote = (quote) => { setSelected(quote); setQuotes((items) => items.map((item) => item._id === quote._id ? quote : item)); };
  return <section className="py-10"><p className="text-sm font-semibold text-leaf">{user.role === "supplier" ? "INCOMING RFQS" : "PROCUREMENT"}</p><h1 className="mt-2 text-4xl text-forest">Quotations</h1><div className="mt-7 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><div className="card divide-y overflow-hidden">{quotes.map((quote) => <button key={quote._id} className={`w-full p-4 text-left hover:bg-mist ${selected?._id === quote._id ? "bg-mist" : ""}`} onClick={() => setSelected(quote)}><div className="flex justify-between gap-2"><b>{quote.requirements.productName}</b><Status value={quote.status} /></div><p className="mt-1 text-sm text-slate-500">{user.role === "supplier" ? quote.customer?.companyName || quote.customer?.name : quote.supplier?.companyName}</p></button>)}{!quotes.length && <div className="p-6"><Empty title="No quotations yet" /></div>}</div><div>{selected ? <QuotePanel quote={selected} role={user.role} onUpdated={updateQuote} /> : <div className="card grid min-h-64 place-items-center text-slate-500">Select a quotation to view its details.</div>}</div></div></section>;
}

function QuotePanel({ quote, role, onUpdated }) {
  const { register, handleSubmit, formState: { isSubmitting } } = useForm({ defaultValues: { quotedAmount: quote.quotedAmount || "", currency: quote.currency || "USD", leadTimeDays: quote.leadTimeDays || "", validUntil: quote.validUntil?.slice(0, 10) || "", supplierMessage: quote.supplierMessage || "" } });
  const update = async (payload) => { try { const { data } = await api.patch(`/quotes/${quote._id}`, payload); toast.success("Quotation updated."); onUpdated(data.quote); } catch (error) { toast.error(error.response?.data?.message || "Could not update quotation."); } };
  const submit = (values) => update({ ...values, quotedAmount: Number(values.quotedAmount), leadTimeDays: Number(values.leadTimeDays), status: "quoted" });
  return <div className="space-y-5"><div className="card p-6"><div className="flex justify-between"><h2 className="text-xl">{quote.requirements.productName}</h2><Status value={quote.status} /></div><p className="mt-3 text-sm">Quantity: <b>{quote.requirements.quantity}</b></p>{quote.requirements.notes && <p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm">Customer note: {quote.requirements.notes}</p>}{role === "supplier" && quote.status === "requested" && <form className="mt-5 grid gap-3 md:grid-cols-2" onSubmit={handleSubmit(submit)}><Field label="Total amount"><input className="input" required type="number" min="0" step="0.01" {...register("quotedAmount")} /></Field><Field label="Currency"><input className="input" {...register("currency")} /></Field><Field label="Lead time days"><input className="input" required type="number" min="0" {...register("leadTimeDays")} /></Field><Field label="Valid until"><input className="input" type="date" {...register("validUntil")} /></Field><label className="md:col-span-2"><span className="label">Message to customer</span><textarea className="input min-h-20" {...register("supplierMessage")} /></label><button className="btn-primary md:col-span-2" disabled={isSubmitting}>Send quotation</button><button className="text-left text-sm text-red-600 md:col-span-2" type="button" onClick={() => update({ status: "rejected" })}>Decline request</button></form>}{role === "customer" && quote.status === "quoted" && <div className="mt-5 flex flex-wrap gap-3"><p className="w-full text-sm">Offer: <b>{quote.currency} {quote.quotedAmount}</b> · {quote.leadTimeDays} day lead time</p><button className="btn-primary" onClick={() => update({ status: "accepted" })}>Accept quotation</button><button className="btn-secondary" onClick={() => update({ status: "rejected" })}>Reject</button></div>}{role === "customer" && quote.status === "requested" && <button className="mt-5 text-sm text-red-600" onClick={() => update({ status: "cancelled" })}>Cancel request</button>}</div><MessageThread quoteId={quote._id} /></div>;
}

function MessageThread({ quoteId }) {
  const { user } = useAuth(); const [messages, setMessages] = useState(null); const [body, setBody] = useState("");
  useEffect(() => { let active = true; const load = async () => { try { const { data } = await api.get(`/quotes/${quoteId}/messages`); if (active) setMessages(data.messages); } catch { if (active) setMessages([]); } }; const receive = (message) => { if (String(message.quote) !== quoteId) return; setMessages((items) => items && items.some((item) => item._id === message._id) ? items : [...(items || []), message]); }; load(); socket.connect(); socket.emit("quote:join", quoteId); socket.on("message:new", receive); return () => { active = false; socket.emit("quote:leave", quoteId); socket.off("message:new", receive); }; }, [quoteId]);
  const send = async (event) => { event.preventDefault(); if (!body.trim()) return; try { const { data } = await api.post(`/quotes/${quoteId}/messages`, { body }); setMessages((items) => items && items.some((message) => message._id === data.message._id) ? items : [...(items || []), data.message]); setBody(""); } catch (error) { toast.error(error.response?.data?.message || "Could not send message."); } };
  return <section className="card p-5"><h3 className="font-semibold">Buyer–supplier conversation</h3><div className="mt-4 max-h-64 space-y-3 overflow-y-auto">{messages === null ? <p className="text-sm text-slate-500">Loading messages...</p> : messages.length ? messages.map((message) => <div key={message._id} className={`max-w-[85%] rounded-xl p-3 text-sm ${message.sender?._id === user._id ? "ml-auto bg-forest text-white" : "bg-mist"}`}><p>{message.body}</p><span className="mt-1 block text-xs opacity-70">{message.sender?.name}</span></div>) : <p className="text-sm text-slate-500">No messages yet. Start the conversation.</p>}</div><form className="mt-4 flex gap-2" onSubmit={send}><input className="input" value={body} onChange={(event) => setBody(event.target.value)} placeholder="Write a message..." maxLength="2000" /><button className="btn-primary">Send</button></form></section>;
}
